image: Visual Studio 2013
clone_depth: 50
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
  - nuget && nuget restore BuildAMation.sln & exit 0
environment:
  matrix:
  - configuration: Release
    platform: Any CPU
