image: Visual Studio 2017
clone_depth: 1
configuration: Release
platform: Any CPU
before_build:
  - cmd: dotnet --version
build_script:
  - dotnet clean BuildTest\BuildTest.csproj
  - dotnet publish BuildTest\BuildTest.csproj
