notifications:
  email:
     on_success: change
     on_failure: always
language: csharp
solution: BuildAMation.sln
matrix:
  include:
  - os: linux
    mono: latest
    script:
      - msbuild /p:Configuration=Release BuildAMation.sln && python codingtools/test_bam.py && source env.sh && cd tests && python runtests.py --C.bitdepth=64 -b Native -c debug -c profile -j0
  # DotNetCore axis removed as the referenced assemblies in the .sln
  # are incorrect for this
  #- os: linux
  #  mono: none
  #  dotnet: 2.1.4
  #  script:
  #    - dotnet msbuild /p:Configuration=Release BuildAMation.sln
  #    - python codingtools/test_bam.py
