language: csharp
solution: BuildAMation.sln
matrix:
  include:
  - os: linux
    mono: latest
    script:
      - msbuild /p:Configuration=Release BuildAMation.sln && python codingtools/test_bam.py && python tests/runtests.py -k -c debug -t Test5
  # DotNetCore axis removed as the referenced assemblies in the .sln
  # are incorrect for this
  #- os: linux
  #  mono: none
  #  dotnet: 2.1.4
  #  script:
  #    - dotnet msbuild /p:Configuration=Release BuildAMation.sln
  #    - python codingtools/test_bam.py
